config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'chats#index'
  resources :chats

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @chats = Chat.all
    respond_with(@chats)
  end

  def show
    MessageRocket.on :subscription_request do |request|
      if request.channel == '/chats/' + @chat.id.to_s

        request.permit
      else
        request.deny
      end
    end

    respond_with(@chat)
  end

  def new
    @chat = Chat.new
    respond_with(@chat)
  end

  def edit
  end

  def create
    @chat = Chat.new(chat_params)
    @chat.save
    respond_with(@chat)
  end

  def update
    @chat.update(chat_params)
    respond_with(@chat)
  end

  def destroy
    @chat.destroy
    respond_with(@chat)
  end

  private
    def set_chat
      @chat = Chat.find(params[:id])
    end

    def chat_params
      params[:chat]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.slim
= form_for @chat do |f|
  - if @chat.errors.any?
    #error_explanation
      h2 = "#{pluralize(@chat.errors.count, "error")} prohibited this chat from being saved:"
      ul
        - @chat.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/chats/edit.html.slim
h1 Editing chat

== render 'form'

= link_to 'Show', @chat
'|
= link_to 'Back', chats_path

app/views/chats/index.html.slim
h1 Listing chats

table
  thead
    tr
      th
      th
      th

  tbody
    - @chats.each do |chat|
      tr
        td = link_to 'Show', chat
        td = link_to 'Edit', edit_chat_path(chat)
        td = link_to 'Destroy', chat, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Chat', new_chat_path

app/views/chats/new.html.slim
h1 New chat

== render 'form'

= link_to 'Back', chats_path

app/views/chats/show.html.slim
.row
  .chat-container
    /.pull-right = @chat.user.email
    h4 = @chat.title
    .chat-window
      .chat-item-container
        .chat-item
          p.text
            | Once upon a midnight dreary, while I pondered, weak and weary,
               Over many a quaint and curious volume of forgotten lore,
                While I nodded, nearly napping, suddenly there came a tapping,
                 As of some one gently rapping, rapping at my chamber door.
                  Tis some visitor," I muttered, "tapping at my chamber door —
                   Only this, and nothing more."
        .chat-item
          p.text
            | Once upon a midnight dreary, while I pondered, weak and weary,
               Over many a quaint and curious volume of forgotten lore,
                While I nodded, nearly napping, suddenly there came a tapping,
                 As of some one gently rapping, rapping at my chamber door.
                  Tis some visitor," I muttered, "tapping at my chamber door —
                   Only this, and nothing more."
        .chat-item
          p.text
            | Once upon a midnight dreary, while I pondered, weak and weary,
               Over many a quaint and curious volume of forgotten lore,
                While I nodded, nearly napping, suddenly there came a tapping,
                 As of some one gently rapping, rapping at my chamber door.
                  Tis some visitor," I muttered, "tapping at my chamber door —
                   Only this, and nothing more."
    .chat-input
      .input-group
        Form
          input#cmd.form-control type="text" placeholder="What do we do now?"
        span.input-group-btn
          button.btn.btn-default type="button" Go!


/= link_to 'Edit', edit_chat_path(@game)

app/views/layouts/_navbar.slim
nav.navbar.navbar-sub role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target="#menu" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Subspace', root_path, class: 'navbar-brand'

    #menu.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li
            = link_to 'New Chat', new_chat_path
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false"
              = current_user.email
              span.caret
            ul.dropdown-menu role="menu"
              li
                a href="#"
                  | My Chats
              // Todo show all games that belong to a user
              li
                = link_to 'Profile', edit_user_registration_path
              li.divider
              li
                = link_to 'Log Out', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'Register', new_user_registration_path
          li
            = link_to 'Log In', new_user_session_path

app/views/layouts/application.slim
html lang='en'
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'A'}"
    title = content_for?(:title) ? yield(:title) : 'Subspace'
    == message_rocket_link_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body{id="#{params[:controller]}" class="#{params[:action]}"}
    - if notice
      p.notice = notice
    - if alert
      p.alert = alert
    = render 'layouts/navbar'
    .container
      = yield